### ISSUE TITLE
Preview (is) was dead

### ISSUE THREAD

**Issue by sGerli** [pebble-dev/rebble-store#87] opened 2016-12-27 15:19 UTC
We need to put this gh-pages in a subdomain like `store.rebble.io` to fix preview URL issues. I'm going to revert and will not make the changes until this is done.

**Comment by ishotjr** [comment] 2016-12-27 15:24
@sGerli I'm not sure I understand - we already have it on `rebble.io` i.e.:

http://rebble.io/rebble-store/

Can you clarify the actual issue, and how a subdomain would behave differently vs. `rebble.io`?  Thanks!!! :bowtie: :heart:

**Comment by sGerli** [comment] 2016-12-27 15:29
We need a subdomain because vue looks for static files and other dependencies in the root folder `rebble.io` and they aren't in there and because of this it doesn't work.

**Comment by ishotjr** [comment] 2016-12-27 15:35
@sGerli OH! So the issue is the sub-folder vs. the domain itself - understood - will have this set up in a few hours... :sweat_smile:

**Comment by ishotjr** [comment] 2016-12-28 03:35
@sGerli I've submitted https://github.com/pebble-dev/rebble-store/pull/88 and made the necessary DNS changes for http://rebble.io/rebble-store/ to resolve as http://store.rebble.io/ - please merge and confirm that everything's working as desired as a result.  Thanks! :bowtie: 🚀

**Comment by sGerli** [comment] 2016-12-28 04:20
Ok, thanks. Merged and I will confirm tomorrow, subdomain is live

**Comment by ishotjr** [comment] 2016-12-28 04:21
@sGerli it's resolving for me already:

http://store.rebble.io/

:bowtie: 🚀

**Comment by Zetaphor** [comment] 2016-12-28 13:41
Confirmed, we're live!

**Closed as completed by Zetaphor** 2016-12-28 13:41 UTC
Labels: bug, vue
